name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.release.outputs.published }}
      publishedPackages: ${{ steps.release.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: pagopa/dx/.github/actions/node-setup@0fd2b15f5b61751fa433be93682e4a48779b600b
        env:
          TURBO_CACHE_DIR: .turbo

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Tag
        id: changesets
        uses: changesets/action@c8bada60c408975afd1a20b3db81d6eee6789308 # v1.4.9
        with:
          version: pnpm run version
          publish: pnpm run release
          commit: "ci(changesets): version packages"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release output
        id: release
        run: |
          # intermediate variable necessary to avoid quotes around the array
          # that prevented the fromJson function to work correctly
          publishedPackages=${{toJSON(steps.changesets.outputs.publishedPackages)}}

          echo 'published=${{steps.changesets.outputs.published}}' >> "$GITHUB_OUTPUT"
          echo "publishedPackages=$publishedPackages" >> "$GITHUB_OUTPUT"

  publish:
    name: Publish
    needs: [release]
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.publishedPackages) }}
    steps:
      - name: Check internal packages
        # they are not supposed to be published
        if: ${{ startsWith(matrix.package.name, '@') }}
        run: |
          echo '::warning title=Internal::Package ${{ matrix.package.name }} is not supposed to be published'
          echo "SKIP_RELEASE_NO_PACK=true" >> $GITHUB_ENV

      - name: Checkout Repo
        if: ${{ env.SKIP_RELEASE_NO_PACK != 'true' }}
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: pagopa/dx/.github/actions/node-setup@0fd2b15f5b61751fa433be93682e4a48779b600b
        env:
          TURBO_CACHE_DIR: .turbo

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ env.SKIP_RELEASE_NO_PACK != 'true' }}
        run: pnpm build --filter ${{ matrix.package.name }}

      - name: Package
        if: ${{ env.SKIP_RELEASE_NO_PACK != 'true' }}
        run: pnpm workspace ${{ matrix.package.name }} run build:package

      - name: Create release
        if: ${{ env.SKIP_RELEASE_NO_PACK != 'true' }}
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          draft: true
          files: apps/${{ matrix.package.name == 'io-ipatente-vehicles' && 'vehicles' || matrix.package.name == 'io-ipatente-licences' && 'licences' || matrix.package.name == 'io-ipatente-payments' && 'payments' || matrix.package.name == 'io-ipatente-practices' && 'practices' || matrix.package.name }}/${{ matrix.package.name }}-${{ matrix.package.version }}.zip
          tag_name: ${{ matrix.package.name }}@${{ matrix.package.version }}
          generate_release_notes: true
